### ISSUE TITLE
AttributeError: module 'kraken.node_actions' has no attribute 'common_node_functions'

### ISSUE THREAD

**Issue by napoleon-diaz** [cloud-bulldozer/kraken#105]
Hey guys, I am running into an issue when running a chaos test, do you know if this is related to a bug or something like that?

thanks in advance!

```
Traceback (most recent call last):
  File "run_kraken.py", line 15, in <module>
    import kraken.node_actions.common_node_functions as nodeaction
  File "/root/kraken/kraken/node_actions/common_node_functions.py", line 10, in <module>
    from kraken.node_actions.aws_node_scenarios import aws_node_scenarios
  File "/root/kraken/kraken/node_actions/aws_node_scenarios.py", line 6, in <module>
    import kraken.node_actions.common_node_functions as nodeaction
AttributeError: module 'kraken.node_actions' has no attribute 'common_node_functions'
```

**Comment by chaitanyaenr** [comment]
@napoleon-diaz Thanks for reporting the issue, @obrienrobert mentioned about this issue recently and looks like we are hitting this only when using the containerized version of kraken vs standalone version seems to be working fine. We are actively working on fixing it. We will have a fix out soon. Thanks.

**Comment by napoleon-diaz** [comment]
wow, that was fast! thanks a lot @chaitanyaenr !

**Comment by chaitanyaenr** [comment]
@napoleon-diaz @obrienrobert  #107 should fix the issue. Here is the temporary image with the patch which can be used for testing: quay.io/chaitanyaenr/kraken:latest until the patch is in. Thanks.

**Comment by napoleon-diaz** [comment]
thank you @chaitanyaenr, I tested the image and now I am getting the following
```
[ndiaz@LAPTOP-NDIAZ cp4saas-chaos-tester (SECCON-12198a)]$ ./chaos.sh --kraken-config scenarios/common/litmus/rbac.yml
Wed Jun 16 23:44:01 UTC 2021 [chaos.sh]: Creating chaos docker network.
bd52cc6cd5d55c3987d401cea28555118e31a87928358096a9c4b2d0e94f8f45
Wed Jun 16 23:44:02 UTC 2021 [chaos.sh]: Building kraken image...
Wed Jun 16 23:44:15 UTC 2021 [chaos.sh]: Finished building kraken image.
Wed Jun 16 23:44:15 UTC 2021 [chaos.sh]: Starting chaos-kraken container...
Wed Jun 16 23:44:18 UTC 2021 [chaos.sh]: Started chaos-kraken container.
Wed Jun 16 23:44:18 UTC 2021 [chaos.sh]: Following execution of chaos-kraken...
2021-06-16 23:44:18,834 [INFO] Starting kraken
 _              _
| | ___ __ __ _| | _____ _ __
| |/ / '__/ _` | |/ / _ \ '_ \
|   <| | | (_| |   <  __/ | | |
|_|\_\_|  \__,_|_|\_\___|_| |_|


Traceback (most recent call last):
  File "run_kraken.py", line 144, in <module>
    main(options.cfg)
  File "run_kraken.py", line 27, in main
    config = yaml.full_load(f)
  File "/usr/local/lib64/python3.6/site-packages/yaml/__init__.py", line 142, in full_load
    return load(stream, FullLoader)
  File "/usr/local/lib64/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib64/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 43, in get_single_node
    event.start_mark)
yaml.composer.ComposerError: expected a single document in the stream
  in "config/config.yaml", line 2, column 1
but found another document
  in "config/config.yaml", line 11, column 1
Wed Jun 16 23:44:19 UTC 2021 [chaos.sh]: chaos-kraken finished.
Wed Jun 16 23:44:19 UTC 2021 [chaos.sh]: Inspecting chaos-kraken execution results...
Wed Jun 16 23:44:19 UTC 2021 [chaos.sh]: chaos-kraken exited with non-zero exit code. Presuming failures.
Wed Jun 16 23:44:19 UTC 2021 [chaos.sh]: One of more errors found after chaos-kraken execution.
Wed Jun 16 23:44:19 UTC 2021 [chaos.sh]: Exiting with error.
Wed Jun 16 23:44:19 UTC 2021 [chaos.sh]: Cleaning up chaos-cerberus container.
Wed Jun 16 23:44:20 UTC 2021 [chaos.sh]: Cleaning up chaos-kraken container.
Wed Jun 16 23:44:21 UTC 2021 [chaos.sh]: Cleaning up chaos network.
```

**Comment by napoleon-diaz** [comment]
I am using a wrapper called chaos.sh, and I am trying a different scenario I am getting this error

```
[ndiaz@LAPTOP-NDIAZ cp4saas-chaos-tester (SECCON-12198a)]$ ./chaos.sh --kraken-config config/kraken/suites/uds/trigger_synthetics_udiendpoints_redis.yml
Wed Jun 16 23:49:29 UTC 2021 [chaos.sh]: Creating chaos docker network.
2577a944746bdf5dea8b7928862d0f73dffec56bc6ef603094f89d708b9cc132
Wed Jun 16 23:49:30 UTC 2021 [chaos.sh]: Building kraken image...
Wed Jun 16 23:49:36 UTC 2021 [chaos.sh]: Finished building kraken image.
Wed Jun 16 23:49:36 UTC 2021 [chaos.sh]: Starting chaos-kraken container...
Wed Jun 16 23:49:40 UTC 2021 [chaos.sh]: Started chaos-kraken container.
Wed Jun 16 23:49:40 UTC 2021 [chaos.sh]: Following execution of chaos-kraken...
2021-06-16 23:49:40,556 [INFO] Starting kraken
 _              _
| | ___ __ __ _| | _____ _ __
| |/ / '__/ _` | |/ / _ \ '_ \
|   <| | | (_| |   <  __/ | | |
|_|\_\_|  \__,_|_|\_\___|_| |_|


2021-06-16 23:49:40,574 [INFO] Initializing client to talk to the Kubernetes cluster
Traceback (most recent call last):
  File "run_kraken.py", line 144, in <module>
    main(options.cfg)
  File "run_kraken.py", line 45, in main
    kubecli.initialize_clients(kubeconfig_path)
  File "/root/kraken/kraken/kubernetes/client.py", line 15, in initialize_clients
    config.load_kube_config(kubeconfig_path)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 753, in load_kube_config
    persist_config=persist_config)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 711, in _get_kube_config_loader
    'Invalid kube-config file. '
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.
Wed Jun 16 23:49:41 UTC 2021 [chaos.sh]: chaos-kraken finished.
```

**Comment by chaitanyaenr** [comment]
Hi @napoleon-diaz, looks like the config is not read, we need to define the scenarios in the kraken config: https://github.com/cloud-bulldozer/kraken/blob/master/config/config.yaml#L6 and pass the config file for the run: https://github.com/cloud-bulldozer/kraken/blob/master/docs/installation.md#run. 

So basically trigger_synthetics_udiendpoints_redis.yml needs be part of the scenarios:https://github.com/cloud-bulldozer/kraken/tree/master/scenarios after which we can tell kraken to load it here: https://github.com/cloud-bulldozer/kraken/blob/master/config/config.yaml. This should do it for the standalone version, we will need to mount it into the container in case of using containerized version for it be part of the container as the scenario is not part of the code base:

$ podman run --name=kraken --net=host -v <path_to_kubeconfig>:/root/.kube/config:Z -v <path_to_kraken_config>:/root/kraken/config/config.yaml:Z -v <scenarios>:/root/kraken/scenarios:Z -d quay.io/openshift-scale/kraken:latest.

Please feel free to let us know in case of any questions. Thanks.

**Comment by napoleon-diaz** [comment]
Thanks, @chaitanyaenr, will do that.

thanks a lot for the info.
