### ISSUE TITLE
Namespace not found error

### ISSUE THREAD

**Issue by paigerube14** [cloud-bulldozer/kraken#176]
While running kraken hub I ran into an issue that when the kube client tries to read namespace status and the namespace doesn't currently exist an error gets outputted and the run stops running.

Need to add a call to properly poll if the namespace currently exists first and then call to the read namespace status and catch an exception if one does occur and handle it properly 

```
2021-11-10 15:56:21,728 [ERROR] Exception when calling CoreV1Api->read_namespace_status: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'f110d50d-5c38-4eed-81d9-68a76cc33096', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'e4323bb0-cdf3-40eb-9abb-966943397326', 'X-Kubernetes-Pf-Prioritylevel-Uid': '61f1e024-5c3c-429b-ad8f-f1e83384f929', 'Date': 'Wed, 10 Nov 2021 15:56:21 GMT', 'Content-Length': '208'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"openshift-etcd\" not found","reason":"NotFound","details":{"name":"openshift-etcd","kind":"namespaces"},"code":404}


Traceback (most recent call last):
  File "run_kraken.py", line 282, in <module>
    main(options.cfg)
  File "run_kraken.py", line 201, in main
    scenarios_list, config, wait_duration, failed_post_scenarios, kubeconfig_path
  File "/root/kraken/kraken/namespace_actions/common_namespace_functions.py", line 63, in run
    failed_post_scenarios = check_active_namespace(killed_namespaces, wait_time)
  File "/root/kraken/kraken/namespace_actions/common_namespace_functions.py", line 73, in check_active_namespace
    response = kubecli.get_namespace_status(namespace_name).strip()
  File "/root/kraken/kraken/kubernetes/client.py", line 45, in get_namespace_status
    return ret.status.phase
AttributeError: 'str' object has no attribute 'status'
```

**Comment by chaitanyaenr** [comment]
Fixed by #181, thanks to @paigerube14!
