### ISSUE TITLE
Initialization error with the latest version

### ISSUE THREAD

**Issue by slaskawi** [cloud-bulldozer/kraken#56]
When trying to run the latest Kraken version (both using Docker and deploying on OpenShift) I get the same error: 

```
2020-12-01 09:46:25,027 [INFO] Starting kraken
2020-12-01 09:46:25,032 [INFO] Initializing client to talk to the Kubernetes cluster
 _              _              
| | ___ __ __ _| | _____ _ __  
| |/ / '__/ _` | |/ / _ \ '_ \ 
|   <| | | (_| |   <  __/ | | |
|_|\_\_|  \__,_|_|\_\___|_| |_|
                               

Traceback (most recent call last):
  File "run_kraken.py", line 316, in <module>
    main(options.cfg)
  File "run_kraken.py", line 238, in main
    kubecli.find_kraken_node()
  File "/root/kraken/kraken/kubernetes/client.py", line 180, in find_kraken_node
    pod_json = json.loads(pod_json_str)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Here are some details on my environment:
```
$ docker version                                                                                                                                                      
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:25 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

$ oc version 
Client Version: 4.4.6
Server Version: 4.5.19
Kubernetes Version: v1.18.3+10e5708

## My kubeconfig appears to be fine:
$ oc get pods         
NAME                                READY   STATUS             RESTARTS   AGE
kraken-deployment-d857c4d4f-btxx8   0/1     CrashLoopBackOff   15         61m
```

Here's how I tried to run it:

```
$ docker run --name=kraken --net=host -v $HOME/.kube/config:/root/.kube/config -v $PWD/chaos/config.yaml:/root/kraken/config/config.yaml quay.io/openshift-scale/kraken:latest
```

**Comment by chaitanyaenr** [comment]
@slaskawi Thanks for reporting the issue. We have been having some problems with the infrastructure on which we run the automated Kraken image builds. We just pushed the latest image into the registry, can you try running the podman method to run it again to see if we hit any issues please? Also what's the config that we are using for this run?

**Comment by chaitanyaenr** [comment]
@slaskawi The issue should be fixed now. Closing the issue, please feel free reopen if there are any issues with running the Kraken. Thanks.
