### ISSUE TITLE
can not run in the openshift 4.7 with latest images

### ISSUE THREAD

**Issue by ericnie2015** [cloud-bulldozer/kraken#79]
I run it in my local openshift cluster, can not connect to internet, the error is
[root@helper ~]# podman logs -f kraken
2021-03-31 06:33:30,085 [INFO] Starting kraken
2021-03-31 06:33:30,091 [INFO] Initializing client to talk to the Kubernetes cluster
2021-03-31 06:33:31,060 [INFO] Fetching cluster info
2021-03-31 06:33:31,977 [INFO] 
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.7.0     True        False         6d17h   Cluster version is 4.7.0
Kubernetes control plane is running at https://api.ocp4.example.com:6443

2021-03-31 06:33:31,978 [INFO] Daemon mode not enabled, will run through 1 iterations

2021-03-31 06:33:31,978 [INFO] Executing scenarios for iteration 0
2021-03-31 06:33:32,481 [INFO] Scenario: scenarios/etcd.yml has been successfully injected!
2021-03-31 06:33:32,481 [INFO] Waiting for the specified duration: 60
2021-03-31 06:34:32,965 [INFO] Scenario: scenarios/regex_openshift_pod_kill.yml has been successfully injected!
2021-03-31 06:34:32,965 [INFO] Waiting for the specified duration: 60
 _              _              
| | ___ __ __ _| | _____ _ __  
| |/ / '__/ _` | |/ / _ \ '_ \ 
|   <| | | (_| |   <  __/ | | |
|_|\_\_|  \__,_|_|\_\___|_| |_|
                               

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 39.2.0 (/usr/lib/python3.6/site-packages), Requirement.parse('setuptools>=40.3.0'), {'google-auth'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/powerfulseal", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'setuptools>=40.3.0' distribution was not found and is required by google-auth

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 39.2.0 (/usr/lib/python3.6/site-packages), Requirement.parse('setuptools>=40.3.0'), {'google-auth'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/powerfulseal", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'setuptools>=40.3.0' distribution was not found and is required by google-auth

Traceback (most recent call last):
  File "run_kraken.py", line 403, in <module>
    main(options.cfg)
  File "run_kraken.py", line 351, in main
    node_scenarios(scenarios_list, config)
  File "run_kraken.py", line 212, in node_scenarios
    node_scenario_object = get_node_scenario_object(node_scenario)
  File "run_kraken.py", line 32, in get_node_scenario_object
    return aws_node_scenarios()
  File "/root/kraken/kraken/node_actions/aws_node_scenarios.py", line 66, in __init__
    self.aws = AWS()
  File "/root/kraken/kraken/node_actions/aws_node_scenarios.py", line 12, in __init__
    self.boto_client = boto3.client('ec2')
  File "/usr/local/lib/python3.6/site-packages/boto3/__init__.py", line 93, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 838, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 87, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.6/site-packages/botocore/args.py", line 73, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python3.6/site-packages/botocore/args.py", line 154, in compute_client_args
    s3_config=s3_config,
  File "/usr/local/lib/python3.6/site-packages/botocore/args.py", line 220, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/args.py", line 303, in _resolve_endpoint
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 402, in resolve
    service_name, region_name)
  File "/usr/local/lib/python3.6/site-packages/botocore/regions.py", line 134, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python3.6/site-packages/botocore/regions.py", line 148, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
^C

my config is like this
====================================
[root@helper ~]# cat config.yaml
kraken:
    kubeconfig_path: /data/install/auth/kubeconfig                    # Path to kubeconfig
    exit_on_failure: False                                 # Exit when a post action scenario fails
    chaos_scenarios:                                         # List of policies/chaos scenarios to load
        -   pod_scenarios:                                 # List of chaos pod scenarios to load
            - -    scenarios/etcd.yml
            - -    scenarios/regex_openshift_pod_kill.yml
              -    scenarios/post_action_regex.py
        -   node_scenarios:                                # List of chaos node scenarios to load
            -   scenarios/node_scenarios_example.yml
        -   pod_scenarios:
            - -    scenarios/openshift-apiserver.yml
            - -    scenarios/openshift-kube-apiserver.yml
        -   time_scenarios:                                # List of chaos time scenarios to load
            - scenarios/time_scenarios_example.yml

cerberus:
    cerberus_enabled: False                                # Enable it when cerberus is previously installed
    cerberus_url:                                          # When cerberus_enabled is set to True, provide the url where cerberus publishes go/no-go signal

performance_monitoring:
    deploy_dashboards: False                              # Install a mutable grafana and load the performance dashboards. Enable this only when running on OpenShift
    repo: "https://github.com/cloud-bulldozer/performance-dashboards.git"

tunings:
    wait_duration: 60                                      # Duration to wait between each chaos scenario
    iterations: 1                                          # Number of times to execute the scenarios
    daemon_mode: False                                     # Iterations are set to infinity which means that the kraken will cause chaos forever

Do you have some suggestion?

**Comment by ericnie2015** [comment]
the running command is 
[root@helper ~]# podman run --name=kraken --net=host -v /data/install/auth/kubeconfig:/root/.kube/config:Z -v /root/config.yaml:/root/kraken/config/config.yaml:Z -d quay.io/openshift-scale/kraken:latest

**Comment by chaitanyaenr** [comment]
@ericnie2015 Hello, thanks for reporting the issue. https://github.com/cloud-bulldozer/kraken/pull/83 should fix it. We will let you know once it gets merged/Kraken images have been updated. Thanks.

**Comment by chaitanyaenr** [comment]
@ericnie2015 Thanks again for opening the issue, https://github.com/cloud-bulldozer/kraken/pull/83 should fix the images. Closing the issue, please feel free to reopen if there are any issues with running the tool. Thanks.
